#!/bin/sh
set -euo pipefail

export PATH="$PATH:/opt/aws_installed/v2/2.26.7/dist/:/opt/"

cd $LAMBDA_TASK_ROOT

source $(dirname "$0")/"$(echo $_HANDLER | cut -d. -f1).sh"

while true; do

    # Request the next event from the Lambda runtime
    HEADERS="$(mktemp)"
    EVENT_DATA=$(curl -v -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
    INVOCATION_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

    # echo "------ passing EVENT_DATA=$(echo $EVENT_DATA | jq .)"
    RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) "$EVENT_DATA")
    # echo "output from handler=$(echo $RESPONSE)"

    curl -v -sS -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$INVOCATION_ID/response" -d "$RESPONSE"

done
